//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeriesReminderConsole2.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SerieInfo", Namespace="http://schemas.datacontract.org/2004/07/SerieDatabase")]
    [System.SerializableAttribute()]
    public partial class SerieInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime AirTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EpisodeNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SeasonField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime AirTime {
            get {
                return this.AirTimeField;
            }
            set {
                if ((this.AirTimeField.Equals(value) != true)) {
                    this.AirTimeField = value;
                    this.RaisePropertyChanged("AirTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EpisodeName {
            get {
                return this.EpisodeNameField;
            }
            set {
                if ((object.ReferenceEquals(this.EpisodeNameField, value) != true)) {
                    this.EpisodeNameField = value;
                    this.RaisePropertyChanged("EpisodeName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Season {
            get {
                return this.SeasonField;
            }
            set {
                if ((this.SeasonField.Equals(value) != true)) {
                    this.SeasonField = value;
                    this.RaisePropertyChanged("Season");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllSeries", ReplyAction="http://tempuri.org/IService1/GetAllSeriesResponse")]
        System.Collections.Generic.Dictionary<string, int> GetAllSeries();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllSeries", ReplyAction="http://tempuri.org/IService1/GetAllSeriesResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<string, int>> GetAllSeriesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SearchSeries", ReplyAction="http://tempuri.org/IService1/SearchSeriesResponse")]
        SeriesReminderConsole2.ServiceReference1.SerieInfo[] SearchSeries(string title);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SearchSeries", ReplyAction="http://tempuri.org/IService1/SearchSeriesResponse")]
        System.Threading.Tasks.Task<SeriesReminderConsole2.ServiceReference1.SerieInfo[]> SearchSeriesAsync(string title);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Timer", ReplyAction="http://tempuri.org/IService1/TimerResponse")]
        string Timer(System.DateTime DinDato);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Timer", ReplyAction="http://tempuri.org/IService1/TimerResponse")]
        System.Threading.Tasks.Task<string> TimerAsync(System.DateTime DinDato);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : SeriesReminderConsole2.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<SeriesReminderConsole2.ServiceReference1.IService1>, SeriesReminderConsole2.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.Dictionary<string, int> GetAllSeries() {
            return base.Channel.GetAllSeries();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<string, int>> GetAllSeriesAsync() {
            return base.Channel.GetAllSeriesAsync();
        }
        
        public SeriesReminderConsole2.ServiceReference1.SerieInfo[] SearchSeries(string title) {
            return base.Channel.SearchSeries(title);
        }
        
        public System.Threading.Tasks.Task<SeriesReminderConsole2.ServiceReference1.SerieInfo[]> SearchSeriesAsync(string title) {
            return base.Channel.SearchSeriesAsync(title);
        }
        
        public string Timer(System.DateTime DinDato) {
            return base.Channel.Timer(DinDato);
        }
        
        public System.Threading.Tasks.Task<string> TimerAsync(System.DateTime DinDato) {
            return base.Channel.TimerAsync(DinDato);
        }
    }
}
